### PR TITLE
Notes

### PR DESCRIPTION
**Pull request by brianlovin**
Hey! Everything here is awesome. A couple notes, but definitely no need to merge this or anything :)

1. No need for constructors and supers if all you need is a `state` property on the class. https://github.com/zachj0hnston/reactfordesignersdotcom/pull/3/commits/36e2f72dc8059fb3b22afde14aebbd73a53b3da4
2. I noticed some unused state here https://github.com/zachj0hnston/reactfordesignersdotcom/pull/3/commits/a48bfc9a5ad600acc7a10749cdcba70e7f33a1db - it's kind of a pain to configure the first time, but if you get yourself a type-checking library like `flow`, paired up with `eslint` running in your code editor it can help you catch a lot of unused stuff like this
3. Here's a minimal implementation of my favorite css-in-js lib, `styled-components`. There are lots of options in this space, but sc is really nice. https://github.com/zachj0hnston/reactfordesignersdotcom/pull/3/commits/8d0c89b9e71bf139ab1bcd736ad3e72cda2a7498 - This introduces the `ThemeProvider` and a `theme` object to hold your variables. You can also see how those variables can get used directly in components.

I really liked this recent post by Brent Jackson: http://jxnblk.com/writing/posts/defining-component-apis-in-react/ - it might offer some ideas on how to split up some of your components and minimize api surface area. For example, I noticed the `ResourceCard` has a *ton* of prop setting, when a lot of that could be extracted into smaller components that are implemented as children. For example:

```js
// instead of
<ResourceCard
  id="treehouse"
  onSelect={this.handleClickCard}
  onClose={this.handleCloseCard}
  isZoomed={this.state.selectedCard==="treehouse"}
  color="#5FCF80"
  title="Treehouse"
  description="React Basics"
  length="3 hours"
  cost="Trial"
  body="Treehouse’s React intro course is easy to follow and
    highly polished. You’ll watch videos and complete code
    excercises in a browser sandbox environment. One drawback,
    the course is a bit dated and they teach you some older
    javascript syntax."
  cta="Start course"
  url="https://teamtreehouse.com/library/react-basics"
/>

// you could have something like
<ResourceCard
  id="treehouse"
  onSelect={this.handleClickCard}
  onClose={this.handleCloseCard}
  isZoomed={this.state.selectedCard==="treehouse"}
>
  <Title>Treehouse</Title>
  <Description>React Basics</Description>
  <Length>3 Hours</Length>
  <Cost>Trial</Cost>
  <Body>
    Treehouse’s React intro course is easy to follow and
    highly polished. You’ll watch videos and complete code
    excercises in a browser sandbox environment. One drawback,
    the course is a bit dated and they teach you some older
    javascript syntax.
  </Body>
  <Button href="https://teamtreehouse.com/library/react-basics">
    Start Course
  </Button>
</ResourceCard>
```

### CODE REVIEW

**Comment by brianlovin** [comment]
Anyways, thanks publishing this repo. I learned a lot digging into your `react-motion` stuff

**Comment by zachj0hnston** [comment]
Learning a lot combing through each change you made. Helps to see things from another point of view.

1. Ah, was wondering why some code examples used the constructor with props while others just threw state in at the beginning. Good to know.

2. I was using that state to see if render had run to know if I could measure the width and height of a div. I think I found another way but didn't remove that state. Added eslint to Atom so should catch stuff like that now.

3. I'm going to keep playing with SC. Seeing how much overhead it takes to add a new class or new global variables makes me a little skeptical of it simplifying my workflow. I do like that it takes a chunk of complexity out of the render function. Maybe I'll get the hang of it after playing a bit more.

4. Moving content from props to children makes sense. Would I need to create a new component for each elements (e.g. <Title />) if I wanted to pass custom style props to it? 

```html
<div
  className="resource-card__title"
  style={{
    fontSize: `${styles.headerFontSize}px`,
    color: TEXTDARKCOLOR,
  }}>
  {this.props.title}
</div>
```

**Comment by brianlovin** [comment]
> Ah, was wondering why some code examples used the constructor with props while others just threw state in at the beginning. Good to know.

Yeah, I've found myself rarely needing the constructor. I've mainly found it useful for modifying class methods with things like a `debounce` or `throttle` - eg 
```js
constructor() {
  super()
  this.search = throttle(this.search, 500);
}
```

> I'm going to keep playing with SC. Seeing how much overhead it takes to add a new class or new global variables makes me a little skeptical of it simplifying my workflow. I do like that it takes a chunk of complexity out of the render function. Maybe I'll get the hang of it after playing a bit more.

and

>Moving content from props to children makes sense. Would I need to create a new component for each elements (e.g. <Title />) if I wanted to pass custom style props to it?

are somewhat related.

Here's my own take on why `styled-components` is valuable:
1. You can entirely colocate your UI components and their styles without worrying about conflicting classes or the cascade from some other component breaking random pieces of your UI as you make changes in one place. So in the example you gave above, yeah you'd probably want a styled component like:

```js
const Title = styled.h1`
  /* styles here */
`
```

2. You can more easily conditionally style components from props by using `styled-components`, because the template literal tag allows you to intersperse javascript. A couple examples:

```js
const Title = styled.h1`
  color: ${props => props.isActive ? '#000' : '#222'};
`
```

Or you could add an entire chunk of css depending on an incoming prop:
```js
import { css } from 'styled-components'

const Title = styled.h1`
  ${props => props.isActive && css`
      outline: 2px solid ${props => props.theme.border.color};
      &:after {
         content: 'ACTIVE';
      }
  `}
`
```

This doesn't necessarily change too much about your existing workflow. You could still envision a project structure like:
```
- components
  - componentA
    - index.js
    - style.js  
```

If you notice yourself writing a lot of the same styled component (rule of threes) then you could break it out into an entirely separate component that can be reused anywhere else in the app.

And of course you could simplify your imports if they get crazy by doing something like:
```js
import * as Styled from './style.js'
// ...
render() {
  return (
    <Styled.Title>Title</Styled.Title>
  )
}
// ...
```

And lastly, since sc is all js, you can write utility css blocks like this:
```js
import { css } from 'styled-components'
export const Truncate = () => css`
  text-overflow: ellipsis;
  overflow: hidden;
  white-space: nowrap;
  min-width: 0;
`

export const Body = styled.p`
  max-width: 560px;
  ${Truncate()}
`
```

And that's probably scratching the surface.

Anyways - there are definitely tradeoffs to all these decisions. Seems like you've got a pretty solid workflow too with scss, so if it's working for you then that's great of course.

https://github.com/jxnblk/styled-system is probably the best learning resource for building out utility ui components based on `styled-components` and lots of other projects by jxnblk are worth digging into.

**Comment by zachj0hnston** [comment]
Mirrored your work on the CardCarousel component. Biggest pain point is referencing the constants via `${props => props.theme.unit.l}`.

Love how the markup looks now so I'll keep pushing on it to see if it fits my style. Thanks for the help so far :)

**Comment by brianlovin** [comment]
> Biggest pain point is referencing the constants via ${props => props.theme.unit.l}.

You can set up a macro in your editor, probably so if you type something like `pt;` it could transform to `${props => props.theme` and put your cursor at the end. Agree completely though that it's quite a lot of extra keystrokes to get those props in.

**Pull request merged**
